<a href="https://colab.research.google.com/github/huda1216/2318029_DataCleansingDATA-CLEANSING-MEDALI-OLIMPIADE-MUSIM-PANAS-1976-2008/blob/main/2318029DataCleansing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 📒Cleansing Data Olimpiade

# **1. Import Library & Load Dataset**
Kita mulai dengan mengimpor pustaka `pandas` dan membaca dataset Olimpiade.

In [ ]:
import pandas as pd
from google.colab import drive

#mount drive
drive.mount('/content/drive')

#path file
file_path = "/content/drive/MyDrive/Colab Notebooks/Summer-Olympic-medals-1976-to-2008.csv"
df = pd.read_csv(file_path, encoding="latin1")

# Tampilkan 5 baris pertama
df.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,City,Year,Sport,Discipline,Event,Athlete,Gender,Country_Code,Country,Event_gender,Medal
0,Montreal,1976.0,Aquatics,Diving,3m springboard,"KÖHLER, Christa",Women,GDR,East Germany,W,Silver
1,Montreal,1976.0,Aquatics,Diving,3m springboard,"KOSENKOV, Aleksandr",Men,URS,Soviet Union,M,Bronze
2,Montreal,1976.0,Aquatics,Diving,3m springboard,"BOGGS, Philip George",Men,USA,United States,M,Gold
3,Montreal,1976.0,Aquatics,Diving,3m springboard,"CAGNOTTO, Giorgio Franco",Men,ITA,Italy,M,Silver
4,Montreal,1976.0,Aquatics,Diving,10m platform,"WILSON, Deborah Keplar",Women,USA,United States,W,Bronze

# **2. Cek Missing Values**
Kita periksa apakah ada data yang kosong (missing values) pada setiap kolom.

In [ ]:
df.isnull().sum()

City            117
Year            117
Sport           117
Discipline      117
Event           117
Athlete         117
Gender          117
Country_Code    117
Country         117
Event_gender    117
Medal           117
dtype: int64

# **3. Cek & Hapus Duplikasi**
Cek apakah ada baris data yang terduplikasi. Jika ada, kita hapus agar data bersih.

In [ ]:
print("Jumlah data duplikat:", df.duplicated().sum())
df = df.drop_duplicates()

Jumlah data duplikat: 117

# **4. Ubah Format Tanggal**
Kolom `Year` masih bertipe float, kita ubah menjadi integer agar lebih rapi.

In [ ]:
df['Year'] = df['Year'].astype('Int64')
df['Year'].head()

0    1976
1    1976
2    1976
3    1976
4    1976
Name: Year, dtype: Int64

# **5. Normalisasi Data Teks**
Agar konsisten, kita ubah semua teks pada kolom bertipe object menjadi huruf kecil (lowercase)
dan hilangkan spasi di awal/akhir.

In [ ]:
for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].str.strip().str.lower()
df.head()

,City,Year,Sport,Discipline,Event,Athlete,Gender,Country_Code,Country,Event_gender,Medal
0,montreal,1976,aquatics,diving,3m springboard,"köhler, christa",women,gdr,east germany,w,silver
1,montreal,1976,aquatics,diving,3m springboard,"kosenkov, aleksandr",men,urs,soviet union,m,bronze
2,montreal,1976,aquatics,diving,3m springboard,"boggs, philip george",men,usa,united states,m,gold
3,montreal,1976,aquatics,diving,3m springboard,"cagnotto, giorgio franco",men,ita,italy,m,silver
4,montreal,1976,aquatics,diving,10m platform,"wilson, deborah keplar",women,usa,united states,w,bronze

# ** 6. Tangani Nilai Negatif**
Kita cek semua kolom numerik, apakah ada nilai negatif. Jika ada, kita ganti dengan `NaN`.

In [ ]:
num_cols = df.select_dtypes(include=['int64','float64']).columns
for col in num_cols:
    negatif = df[df[col] < 0]
    if not negatif.empty:
        print(f"Ada nilai negatif di kolom {col}, diganti jadi NaN")
        df.loc[df[col] < 0, col] = None

# **7. Hapus Kolom Tidak Relevan**
Kolom `Country_Code` dan `Event_gender` tidak terlalu diperlukan, jadi kita hapus.

In [ ]:
df = df.drop(columns=['Country_Code', 'Event_gender'], errors='ignore')
df.head()

,City,Year,Sport,Discipline,Event,Athlete,Gender,Country,Medal
0,montreal,1976,aquatics,diving,3m springboard,"köhler, christa",women,east germany,silver
1,montreal,1976,aquatics,diving,3m springboard,"kosenkov, aleksandr",men,soviet union,bronze
2,montreal,1976,aquatics,diving,3m springboard,"boggs, philip george",men,united states,gold
3,montreal,1976,aquatics,diving,3m springboard,"cagnotto, giorgio franco",men,italy,silver
4,montreal,1976,aquatics,diving,10m platform,"wilson, deborah keplar",women,united states,bronze

# **8. Dataset Setelah Cleansing**
Kita lihat struktur data (`info`) dan 5 baris pertama setelah proses cleansing.

In [ ]:
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
Index: 15316 entries, 0 to 15432
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   City        15315 non-null  object
 1   Year        15315 non-null  Int64
 2   Sport       15315 non-null  object
 3   Discipline  15315 non-null  object
 4   Event       15315 non-null  object
 5   Athlete     15315 non-null  object
 6   Gender      15315 non-null  object
 7   Country     15315 non-null  object
 8   Medal       15315 non-null  object
dtypes: Int64(1), object(8)
memory usage: 1.2+ MB

,City,Year,Sport,Discipline,Event,Athlete,Gender,Country,Medal
0,montreal,1976,aquatics,diving,3m springboard,"köhler, christa",women,east germany,silver
1,montreal,1976,aquatics,diving,3m springboard,"kosenkov, aleksandr",men,soviet union,bronze
2,montreal,1976,aquatics,diving,3m springboard,"boggs, philip george",men,united states,gold
3,montreal,1976,aquatics,diving,3m springboard,"cagnotto, giorgio franco",men,italy,silver
4,montreal,1976,aquatics,diving,10m platform,"wilson, deborah keplar",women,united states,bronze

# **9. Data Enrichment**


---

In [ ]:
# Mapping Medal ke angka
medal_score_map = {"gold": 3, "silver": 2, "bronze": 1}
df["Medal_Score"] = df["Medal"].map(medal_score_map).astype("Int64")

df[["Medal", "Medal_Score"]].head()

    Medal  Medal_Score
0  silver            2
1  bronze            1
2    gold            3
3  silver            2
4  bronze            1

In [ ]:
# 1. Medal_Score
medal_score_map = {"gold": 3, "silver": 2, "bronze": 1}
df["Medal_Score"] = df["Medal"].map(medal_score_map).astype("Int64")

# 2. Decade (dekade dari tahun)
df["Decade"] = ((df["Year"] // 10) * 10).astype("Int64")

# 3. Event_Type (individu vs tim, rule sederhana)
df["Event_Type"] = df["Event"].apply(
    lambda x: "team" if isinstance(x, str) and ("team" in x or "relay" in x) else "individual"
)


# 4. Buat ringkasan agregasi per negara
country_summary = df.groupby("Country").agg(
    Total_Medals=("Medal", "count"),
    Gold=("Medal", lambda x: (x == "gold").sum()),
    Silver=("Medal", lambda x: (x == "silver").sum()),
    Bronze=("Medal", lambda x: (x == "bronze").sum()),
    Total_Score=("Medal_Score", "sum")
).reset_index()


# Tampilkan hasil enrichment
df.head(), country_summary.head()

(       City  Year     Sport Discipline           Event  \
 0  montreal  1976  aquatics     diving  3m springboard
 1  montreal  1976  aquatics     diving  3m springboard
 2  montreal  1976  aquatics     diving  3m springboard
 3  montreal  1976  aquatics     diving  3m springboard
 4  montreal  1976  aquatics     diving    10m platform

                     Athlete Gender        Country   Medal  Medal_Score  \
 0           köhler, christa  women   east germany  silver            2
 1       kosenkov, aleksandr    men   soviet union  bronze            1
 2      boggs, philip george    men  united states    gold            3
 3  cagnotto, giorgio franco    men          italy  silver            2
 4    wilson, deborah keplar  women  united states  bronze            1

    Decade  Event_Type
 0    1970  individual
 1    1970  individual
 2    1970  individual
 3    1970  individual
 4    1970  individual  ,
        Country  Total_Medals  Gold  Silver  Bronze  Total_Score
 0  afghanistan             1     0       0       1            1
 1      algeria            14     4       2       8           24
 2    argentina           153    46      37      70          282
 3      armenia             9     1       1       7           12
 4    australia           798   216     270     312         1500)